kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: producer-21
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafkaproducer
    spec:
      containers:
        - name: producer-21
          image: bsafwene/kafka_producer:latest
          env:
            - name: SLEEPMS
              value: "100"
            - name: TOPIC
              value: "test-21"
