apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs3
  annotations:
        volume.beta.kubernetes.io/storage-class: example-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
