apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kubernetes-scaler
  name: kubernetes-scaler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-scaler
  labels:
    k8s-app: kubernetes-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-scaler
  namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    k8s-app: kubernetes-scaler
  name: kubernetes-scaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kubernetes-scaler
  template:
    metadata:
      labels:
        k8s-app: kubernetes-scaler
    spec:
      serviceAccountName: kubernetes-scaler
      containers:
      - name: kubernetes-scaler
        image: bsafwene/autoscaler:latest
