apiVersion: batch/v1
kind: Job
metadata:
  name: topic-create-test1
spec:
  template:
    metadata:
      name: topic-create-test1
    spec:
      containers:
      - name: kafka
        image: solsson/kafka:0.10.0.1
        command:
        - ./bin/kafka-topics.sh
        - --zookeeper
        - zookeeper:2181
        - --create
        - --topic
        - testTopic
        - --partitions
        - "3"
        - --replication-factor
        - "3"
      restartPolicy: Never
