apiVersion: batch/v1
kind: Job
metadata:
  name: lagging
spec:
  template:
    metadata:
      name: lagging
    spec:
      containers:
      - name: kafka
        image: solsson/kafka:0.10.0.1
        command:
        - ./bin/kafka-consumer-groups.sh
        - --describe
        - --group
        - one 
        - --zookeeper
        - zookeeper:2181
      restartPolicy: Never
