apiVersion: batch/v1
kind: Job
metadata:
  name: listgroups
spec:
  template:
    metadata:
      name: listgroups
    spec:
      containers:
      - name: listgroups
        image: solsson/kafka:0.10.0.1
        command:
        - ./bin/kafka-consumer-groups.sh
        - --list
        - --zookeeper
        - zookeeper:2181
      restartPolicy: Never
