kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dev-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: developer
  namespace: default
- kind: ServiceAccount
  name: elasticsearch
  namespace: default
roleRef:
  kind: Role
  name: dev-root
  apiGroup: rbac.authorization.k8s.io
