---
kind: Service
apiVersion: v1
metadata:
  name: kbnsvc
spec:
  ports:
    - name: http
      port: 5601
      targetPort: 5601
  selector:
    app: kibana
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kbn-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        #image: docker.elastic.co/kibana/kibana:5.4.0
        image: kibana:5.4.0
        env:
           - name: ELASTICSEARCH_URL
             value: "http://elasticsearch:9200/"
