---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: esheapster
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: esheapster
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esheapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: esheapster
    spec:
      serviceAccountName: kubernetes-dashboard
      containers:
      - name: esheapster
        #image: gcr.io/google_containers/heapster-amd64:v1.3.0
        image: quay.io/ecnahc515/heapster:es5 
        #image: quay.io/ecnahc515/heapster:es5-forked
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=elasticsearch:?nodes=http://esmaster-0.esheadless.default.svc:9200&nodes=http://esmaster-1.esheadless.default.svc:9200
