apiVersion: v1
kind: Service
metadata:
  name: esheadless
  labels:
    app: esheadless
spec:
  ports:
  - port: 9300
    name: peer
  - port: 9200
    name: http
  clusterIP: None
  selector:
    app: elasticsearch
