# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
spec:
  ports:
  - port: 9300
    name: discovery
  - port: 9302
    name: discovery2
  - port: 9200
    name: http
  clusterIP: None
  selector:
    app: elasticsearch
