apiVersion: v1
kind: ReplicationController
metadata:
  name: es-rc
  labels:
    app: elasticsearch-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: es
       # image: quay.io/pires/docker-elasticsearch-kubernetes:1.7.1-4
        image: elasticsearch:5.3.1
        env:
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: storage
      volumes:
      - name: storage
        emptyDir: {}
