kubectl delete clusterrolebinding "run-nfs-provisioner" 
kubectl delete clusterrole "nfs-provisioner-runner" 
kubectl delete daemonset "nfs-provisioner" 
kubectl delete deploy "nfs-provisioner" 
kubectl delete service "nfs-provisioner" 
kubectl delete deployment "nfs-provisioner" 
kubectl delete podsecuritypolicy "nfs-provisioner" 
kubectl delete serviceaccount "nfs-provisioner" 
kubectl delete pvc --all
kubectl delete storageclass --all
