apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: test
spec:
  serviceName: nfs-provisioner
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: nginx
        imagePullPolicy: Always
        image: nginx
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/test
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.alpha.kubernetes.io/storage-class: "example-nfs"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: example-nfs
      resources:
        requests:
          storage: 3Gi
